---
version: '3.8'
services:

  nginx:
    image: nginx:latest
    ports:
      - target: 80
        published: 80
        protocol: tcp

  service1:
    image: animal_s1:latest

    build:
      context: ./service1
      dockerfile: Dockerfile

    ports:
      - target: 5000
        published: 5000
        protocol: tcp

  service2:
    image: animal_s2:latest

    build:
      context: ./service2
      dockerfile: Dockerfile

    ports:
      - target: 5001
        published: 5001
        protocol: tcp
...